name: activ
description: My new Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  get_it: ^8.0.3
  equatable: ^2.0.7
  firebase_messaging: ^15.2.5
  firebase_storage: ^12.4.5
  firebase_remote_config: ^5.4.3
  connectivity_plus: ^6.1.4
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  flutter_native_splash: ^2.4.6
  photo_manager: ^3.6.4
  flutter_phoenix: ^1.1.1
  permission_handler: ^12.0.0+1
  go_router: ^15.1.1
  logger: ^2.5.0
  toastification: ^3.0.2
  flutter_svg: ^2.1.0
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  smooth_page_indicator: ^1.2.1
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  url_launcher: ^6.3.1
  shimmer: ^3.0.0
  package_info_plus: ^8.3.0
  flutter_local_notifications: ^19.1.0
  pinput: ^5.0.1
  country_picker:
  image_picker:
  phone_numbers_parser:
  path_provider:
  mapbox_maps_flutter: ^2.8.0
  skeletonizer: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  intl_utils: ^2.8.8
  hive_generator: ^2.0.1
  very_good_analysis: ^7.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/svgs/
    - assets/svgs/interest_icons/
    - assets/svgs/sports_icons/
    - assets/svgs/navigation/
    - assets/images/
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Black.otf
          weight: 900
        - asset: assets/fonts/Urbanist-BlackItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/Urbanist-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Urbanist-ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/Urbanist-Bold.otf
          weight: 700
        - asset: assets/fonts/Urbanist-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Urbanist-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Urbanist-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/Urbanist-Medium.otf
          weight: 500
        - asset: assets/fonts/Urbanist-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Urbanist-Regular.otf
          weight: 400
        - asset: assets/fonts/Urbanist-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Urbanist-Light.otf
          weight: 300
        - asset: assets/fonts/Urbanist-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Urbanist-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Urbanist-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/Urbanist-Thin.otf
          weight: 100
        - asset: assets/fonts/Urbanist-ThinItalic.otf
          weight: 100
          style: italic
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic.ttf

