import 'dart:ui';

abstract class AppColors {
  static const primaryBlue = Color(0xFF24BBC4);
  static Color primaryDisabled = const Color(0xFF24BBC4).withValues(alpha: 0.5);
  static const secondaryBlue = Color(0xFF2C599D);
  static const tertiaryBlue = Color(0xFF172B4D);
  static const primaryAmber = Color(0xFFEF9F27);
  static const textGrey = Color(0xFF7A869A);
  static const amberTertiary = Color(0xFFFFFBC5);
  static const black = Color(0xFF000000);
  static const white = Color(0xFFFFFFFF);
  static const greenPrimary = Color(0xFF14B82C);
  static const greenSecondary = Color(0xFF042F0C);
  static const greenTertiary = Color(0xFF12551E);
  static const greenQuinary = Color(0xFF146721);
  static const greenDisabled = Color(0xFFDBFDDF);
  static const bottomNavBarGreen = Color(0xFF83F292);
  static const greenClassCardBackground = Color(0xFFF0FDF1);
  static const greenChipColor = Color(0xFFB9F9C2);
  static const profileCardBackground = Color(0xFFE6FDE9);
  static const error = Color(0xFFF04438);
  static const textNormal = Color(0xFF6D6D6D);
  static const textFaded = Color(0xFF9E9E9E);
  static const iconBackground = Color(0xFFF6F6F6);
  static const languageExpertChipBackground = Color(0xFFEDEDED);
  static const dividerColor = Color(0xFFF4F5F7);
  static const yellowAccent = Color(0xFFFFF885);
  static const bluePrimary = Color(0xFF00247D);
  static const blueSecondary = Color(0xFFedf2ff);
  static const redPrimary = Color(0xFFAD141E);
  static const redSecondary = Color(0xFFfef1f1);
  static const textDark = Color(0xFF3D3D3D);
  static const disabled = Color(0xFF888888);
  static const disabledSecondary = Color(0xFF454545);
  static const textFieldBorder = Color(0xFFE7E7E7);
  static const messageBorder = Color(0xFFD1D1D1);
  static const messageTimeStamp = Color(0xFF757575);
  static const onGoingClassColor = Color(0x9914B82C);
  static const greenShade1 = Color(0xFF042F0C);
  static const yellowShade1 = Color(0xFFFFED46);
  static const yellowShade2 = Color(0xFFFFFFEA);
  static const drawerTileBackground = Color(0xFFE9F8F9);
  static const redShade1 = Color(0xFFF04438);
  static const darkWhiteBackground = Color(0xFFF2F3F6);

  //new colors
  static const primaryOrange = Color(0xFFE7821D);
  static const secondaryOrange = Color(0xFFFFC89E);
  static const tertiaryOrange = Color(0xFFC96100);
  static const sliderThumb = Color(0xFFED7E1C);
  static const primaryBrown = Color(0xFF4F3422);
  static const secondaryBrown = Color(0xFF926247);
  static const lightYellow = Color(0xFFFFEBC2);
  static const lightBlue = Color(0xFFd6deff);
  static const cloudColor = Color(0xFFF2F5EB);
  static const textFieldGlow = Color(0xFFFE814B);
  static const iconBorderColor = Color(0xFFC9C7C5);
  static const successGreen = Color(0xFF4CA77D);
  static const brownShadow = Color(0xFF4B3425);
  static const disabledText = Color(0xFFACA9A5);
  static const deleteRed = Color(0xFFFC0005);
  static const closeRed = Color(0xFFD32F2F);
  static const drawerIconBackground = Color(0xFFF8F8F8);
  static const checkboxInactive = Color(0xFFCDD4D3);
  static const popupButtonColor = Color(0xFFE76A56);

  //Activ Colors
  static const backgroundWhite = Color(0xFFF7F4F2);
  static const primaryColor = Color(0xFF183227);
  static const secondaryColor = Color(0xFF8B9B74);
  static const textPrimary = Color(0xFF120D26);
  static const textSecondary = Color(0xFF7A869A);
  static const lightText = Color(0xFF747688);
  static const grey = Color(0xFF4D5461);
  static const inactiveProgressBar = Color(0xFFD3D5DA);
  static const activeDetailsProgressBar = Color(0xFF8B9B75);
  static const greyShade1 = Color(0xFFB0B0B0);
  static const greyShade2 = Color(0xFF2a2d38);
  static const greyShade3 = Color(0xFFF6F6F6);
  static const greyShade4 = Color(0xFFF9FAFB);
  static const greyShade5 = Color(0xFFC1C7D0);
  static const greyShade6 = Color(0xFFE5E6EB);
  static const fabBackground = Color(0xFF6C8178);
  static const selectedGender = Color(0xFF8B9B74);
  static const unSelectedGender = Color(0xFFE0E0E0);
}
